version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: oludaredolamu@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - default

  levelup-backend:
    build:
      context: .
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
          target: /app/package.json
    container_name: levelup-backend
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      CHOKIDAR_USEPOLLING: true
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - default
      - levelup-network
    command: npm run start:dev  # Run in development mode with hot reloading

volumes:
  postgres-data:

networks:
  default:
    driver: bridge
  levelup-network:
    external: true  # External network if needed, can be omitted if you don't need it
