version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - default

  levelup-backend:
    build:
      context: .
    container_name: levelup-backend
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_PORT: 5432
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - default
      - levelup-network
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres-data:
networks:
  default: # Define the default network explicitly
    driver: bridge
  levelup-network:
    external: true
